server:
      port: 8090  #配置端口
      address : localhost
      session-timeout: 30
      tomcat.max-threads: 0
      tomcat.uri-encoding: UTF-8


spring :
      application :
          name : spirng-boot-mongodb
      data :
          mongodb :
              uri : mongodb://172.16.2.133:27017/trade






