server:
  port: 8090  #配置端口
  address : localhost
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:  #数据库配置
    url : jdbc:mysql://172.16.2.133:3306/business?useUnicode=true&characterEncoding=utf-8
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver


mybatis:
  configLocation : classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.abin.lee.spring.boot.mybatis.model

# LOGGING
logging:
    level:
       com.ibatis:DEBUG















